### ISSUE TITLE
Showing color code and allow to copy

### ISSUE THREAD

**Issue by ngekoding** [iqbaladinur/color-extractor#1]
Nice to found this awesome work.

I think we need to show the generated color code, and be able to copy the color code with just one click.

The color code can be in hex, rgb, etc...

**Comment by iqbaladinur** [comment]
The copy feature already exist if you click on the result palette.
I hide the color code because i didn't find proper style along side the palette component. It will be very nice if you have some design suggestion.

thanks.

**Comment by ngekoding** [comment]
I just try to visit the site by Mobile Phone, and can’t find anything about color code and copy.

So I make this issue :D 

Need to try with my laptop.
